### PR TITLE
correct SCC apiVersion

### PR DESCRIPTION
**Pull request by pfeifferj**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Looks fine to me. Is the draft PR correct or do you want it to be a real PR?

**Comment by pfeifferj** [comment]
hiya @awels I was going to fill out the PR template later but if this is fine as is, I wouldn't mind skipping ^^

**Comment by awels** [comment]
Yeah I am fine with it as is. Just please change the PR to a normal PR then I can approve.

**Comment by pfeifferj** [comment]
changed it :)

**Pull request merged**
