### PR TITLE
Add tool to generate metrics documentation

### PR DESCRIPTION
**Pull request by machadovilaca**
**What this PR does / why we need it**:

This PR adds a tool to automatically generate documentation with information about exposed metrics.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
So it looks like this is generating metrics for the legacy provisioner, which is deprecated and will be removed at some point in the future.

**Comment by machadovilaca** [comment]
@awels This provisioner is deprecated? Where can I find the new provisioner and the respective metrics?

**Comment by awels** [comment]
So this repo contains a legacy provisioner (for which you just made a PR), AND a CSI driver that does the same job, but within the CSI specification. The legacy provisioner did have some metrics exposed I think, but the CSI driver does not. Anything under /controller is the legacy provisioner, and anything under pkg/hostpath is the csi driver.

**Comment by machadovilaca** [comment]
Since the new driver does not expose any metrics, and the legacy provisioner it's still in use, do you think it's better to go forward with this PR, and later change the tool to fetch the metrics from the CSI driver, or close it and reopen in a later time?

**Pull request closed without merging**
