### PR TITLE
Helm-Chart for kubevirt-hostpath-provisioner

### PR DESCRIPTION
**Pull request by kubelize**
**What this PR does / why we need it**:
Helm is a very practical method to deploy, update and rollback applications and operators in Kubernetes. This PR adds a fully functional helm-chart that allows for a single command to deploy, and by specifying your own values.yaml modify any of the values listed in the README.md for the chart.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
A github-pages deployment which would server as the endpoint for the helm-chart releases would add additional ease of use and quality to the chart. But I leave that up to you if it's something that would interest you :)

**Release note**:

```release-note
Adds a helm-chart to the repository. Will have no effect on the functionality of other content. No user action required.
Chart: kubevirt-hostpath-provisioner
AppVersion: 0.18.0
Chart Version: 0.1.0
```

### CODE REVIEW

**Comment by awels** [comment]
To make the DCO happy, can you `git --amend -s` the `-s` will sign the commit and make the bot happy.

**Comment by awels** [comment]
So I have little to no experience with helm charts. So I can't promise I will maintain it properly. Do we want to create some release artifacts when I release a new version of the provisioner related to the helm charts?

**Comment by moffoso** [comment]
Hey @awels

Unless there are breaking changes to the provisioner, the chart wont need to be updated. The image-tag is set to "latest" per default. (The exeption being if the functionality- of the chart should be extended or improved in some manner)

A release artifact would increase quality of life, especially for example in a CI/CD setup. 
Optimally the workflow with helm would be that you can add the repository the chart is in e.g:
```
helm repo add kubevirt https://kubevirt.github.io/helm-charts
```
and then install while specifyingyour own values
```
helm install kubevirt-hostpath-provider kubevirt/kubevirt-hostpath-provider -f my-custom-values.yam
```
The repo/branch containing the helm-packages then needs and index.yaml used for indexing the charts in the repository.
And finally a release that contains the individual helm-packages. 

If that's not something you would want to maintain, that's understandable. In that case a github-release of the chart would suffice for most  use-cases.

Cheers

**Comment by moffoso** [comment]
I did some testing, and found that pvc's would stay pending due to an an error in the rendering of the daemonset manifest. For some reason that I haven't yet got to the bottom of yet. The issue has been resolved, and pv's are provisioned as expected now. 
-> Bumbed the chart version to 0.1.1

**Comment by awels** [comment]
Okay I have no issues with this, just one question, what is in the tgz file? Is it just a tarred and gzipped version of the helm chart?

**Comment by moffoso** [comment]
> Okay I have no issues with this, just one question, what is in the tgz file? Is it just a tarred and gzipped version of the helm chart?

Indeed it is, it's purely for convenience sake. So that you can install the chart by simply downloading the archive and then running
```
helm install kubevirt-hostpath-provisioner-0.1.0.tgz
```
Optionally you can append `--namespace yournamespace`

**Comment by awels** [comment]
So maybe instead of putting that in the repo, when I make the release, we create the tgz as an artifact, and you can download that to install it?

**Comment by moffoso** [comment]
That would be ideal!

**Comment by moffoso** [comment]
Alright sounds good, I'll probably find time to do that tomorrow.

**Comment by awels** [comment]
I guess you didn't find time, which is fine. Just bumping this so the bot won't start putting stale on it.

**Comment by Bernix01** [comment]
Friendly ping to @kubelize for this PR this feature is very much appreciated :)

**Pull request closed without merging**
