### PR TITLE
Update versions of libraries

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
It looks like it's not actually updating dependencies, can you mention which report prompted this?

**Comment by awels** [comment]
dependabot was reporting older versions of protobuf and yaml.v2 most likely from dependencies. So basically I am just ensuring that dependabot stops bugging me.

**Comment by maya-r** [comment]
okay. I think Go doesn't use all the versions, just the newest one, but fewer false warnings is nice to have.
/lgtm

**Comment by awels** [comment]
Right, the actual library was already there, but somewhere in the dependency tree it had the older versions, and doing the replace removed those from go.sum which was triggering the warnings.

**Pull request merged**
