### PR TITLE
[release-v0.12] Manual backport of #95, #100 for CI to pass

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
CI in `release-v0.12` needs both #95 (yaml filename change) & #100 (`localhost->127.0.0.1` for shuttle and prometheus curl calls) to pass.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
BugFix: No feedback when HPP path is sharing host filesystem
```

### CODE REVIEW

**Comment by maya-r** [comment]
I am confused as to what is happening here because this PR was merged to main, not release-v0.12

**Comment by akalenyu** [comment]
> I am confused as to what is happening here because this PR was merged to main, not release-v0.12

Nice catch, yeah, definitely not what I wanted

**Pull request merged**
