### PR TITLE
Add cluster and functional tests.

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

### CODE REVIEW

**Comment by aglitke** [comment]
It might be interesting to note which providers we actually expect to work but I can't think of a great way to do that and keep it fresh.

**Comment by awels** [comment]
Yeah right now just did basic kubernetes provider, if we decide we can add more providers later.

**Comment by awels** [comment]
Seems like I need to add the OWNERS file before it will allow them to be used. Let me push outside of this PR.

**Pull request merged**
