### PR TITLE
Add functional tests for fsgroup

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Add new functional test ensuring fsGroup is being honored.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Jiawei0227** [comment]
Hey just wondering does hostpath-provisioner supports fsgroup or not right now?

**Comment by awels** [comment]
Hi, it does, the csi driver version anyway.

**Comment by Jiawei0227** [comment]
> Hi, it does, the csi driver version anyway.

Hey sorry what do you mean?

**Comment by awels** [comment]
Around version 0.10 the implementation switched to a CSI driver. It is now at 0.12. There are way you can still invoke the non CSI version. But if you grab the latest and invoke the CSI version of the provisioner, it will support fsGroup. It is pretty dumb about it and essentially will chown all the files in the directory.

**Comment by Jiawei0227** [comment]
Thanks! I was looking at this: https://github.com/kubevirt/hostpath-provisioner/pull/84

So I think we should not set it to None if it does support fsGroup

**Comment by awels** [comment]
You should leave it at the default value, which invokes the k8s code that runs chmod. There is actually no specific code in the driver for it. But yes, I probably forgot to change it (its right in the operator though)

**Pull request merged**
